### PR TITLE
Added laser functions.

### PR DESCRIPTION
**Pull request by retospect**
Added homing and laser functions, also auto-port detection if it is not provided.

### CODE REVIEW

**Comment by ZdenekM** [comment]
Looking forward to see it merged...

**Comment by ZdenekM** [comment]
I tested ```set_home``` and it works but raises AttributeError:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zdenal/arcor2_repos/pydobot/pydobot/dobot.py", line 272, in set_home
    self._set_home(wait)
  File "/home/zdenal/arcor2_repos/pydobot/pydobot/dobot.py", line 267, in _set_home
    return self._send_command(msg,wait)
  File "/home/zdenal/arcor2_repos/pydobot/pydobot/dobot.py", line 81, in _send_command
    expected_idx = struct.unpack_from('L', response.params, 0)[0]
AttributeError: 'NoneType' object has no attribute 'params'
```
Regarding auto-port detection - my Dobot has VID 6790. And by the way, it would be fine to slightly refine the code - for instance you used to unnecessary brackets and 2 space indent.

**Comment by ZdenekM** [comment]
@retospect Issue is fixed in https://github.com/luismesas/pydobot/pull/23. Waiting for homing procedure also works there.

**Comment by retospect** [comment]
That's nice, thanks for polishing it! I don't have a dobot currently, but I've merged your changes, hope they'll make it in soon!

**Pull request merged**
